export const categoryConfig = {
  SPRING: { label: 'Spring', gradient: 'from-green-400 to-emerald-500', bg: 'bg-green-50', badge: 'bg-green-100 text-green-700', emoji: '\u{1F331}' },
  SUMMER: { label: 'Summer', gradient: 'from-yellow-400 to-orange-400', bg: 'bg-yellow-50', badge: 'bg-yellow-100 text-yellow-700', emoji: '\u{2600}\u{FE0F}' },
  AUTUMN: { label: 'Autumn', gradient: 'from-orange-400 to-red-500', bg: 'bg-orange-50', badge: 'bg-orange-100 text-orange-700', emoji: '\u{1F342}' },
  WINTER: { label: 'Winter', gradient: 'from-blue-300 to-cyan-400', bg: 'bg-sky-50', badge: 'bg-sky-100 text-sky-700', emoji: '\u{2744}\u{FE0F}' },
  CHRISTMAS: { label: 'Christmas', gradient: 'from-red-500 to-green-600', bg: 'bg-red-50', badge: 'bg-red-100 text-red-700', emoji: '\u{1F384}' },
  EASTER: { label: 'Easter', gradient: 'from-pink-400 to-purple-400', bg: 'bg-pink-50', badge: 'bg-pink-100 text-pink-700', emoji: '\u{1F430}' },
  SPACE: { label: 'Space', gradient: 'from-indigo-600 to-purple-600', bg: 'bg-indigo-50', badge: 'bg-indigo-100 text-indigo-700', emoji: '\u{1F680}' },
  MATHS: { label: 'Maths', gradient: 'from-blue-500 to-cyan-500', bg: 'bg-blue-50', badge: 'bg-blue-100 text-blue-700', emoji: '\u{1F522}' },
  ENGLISH: { label: 'English', gradient: 'from-purple-500 to-pink-500', bg: 'bg-purple-50', badge: 'bg-purple-100 text-purple-700', emoji: '\u{270D}\u{FE0F}' },
  SCIENCE: { label: 'Science', gradient: 'from-teal-500 to-cyan-600', bg: 'bg-teal-50', badge: 'bg-teal-100 text-teal-700', emoji: '\u{1F52C}' },
  PHONICS: { label: 'Phonics', gradient: 'from-rose-400 to-red-400', bg: 'bg-rose-50', badge: 'bg-rose-100 text-rose-700', emoji: '\u{1F524}' },
  DINOSAURS: { label: 'Dinosaurs', gradient: 'from-amber-600 to-green-700', bg: 'bg-amber-50', badge: 'bg-amber-100 text-amber-700', emoji: '\u{1F995}' },
  ANIMALS: { label: 'Animals', gradient: 'from-lime-500 to-green-600', bg: 'bg-lime-50', badge: 'bg-lime-100 text-lime-700', emoji: '\u{1F43E}' },
  OCEANS: { label: 'Oceans', gradient: 'from-cyan-500 to-blue-600', bg: 'bg-cyan-50', badge: 'bg-cyan-100 text-cyan-700', emoji: '\u{1F30A}' },
  WEATHER: { label: 'Weather', gradient: 'from-sky-400 to-blue-500', bg: 'bg-sky-50', badge: 'bg-sky-100 text-sky-700', emoji: '\u{1F324}\u{FE0F}' },
  HISTORY: { label: 'History', gradient: 'from-amber-700 to-yellow-800', bg: 'bg-amber-50', badge: 'bg-amber-100 text-amber-700', emoji: '\u{1F3DB}\u{FE0F}' },
  GEOGRAPHY: { label: 'Geography', gradient: 'from-emerald-500 to-teal-600', bg: 'bg-emerald-50', badge: 'bg-emerald-100 text-emerald-700', emoji: '\u{1F30D}' },
  NATURE: { label: 'Nature', gradient: 'from-green-500 to-lime-600', bg: 'bg-green-50', badge: 'bg-green-100 text-green-700', emoji: '\u{1F33F}' },
  ART: { label: 'Art', gradient: 'from-fuchsia-500 to-pink-500', bg: 'bg-fuchsia-50', badge: 'bg-fuchsia-100 text-fuchsia-700', emoji: '\u{1F3A8}' },
  MUSIC: { label: 'Music', gradient: 'from-violet-500 to-purple-500', bg: 'bg-violet-50', badge: 'bg-violet-100 text-violet-700', emoji: '\u{1F3B5}' },
  COMPUTING_LABELS: { label: 'Computing', gradient: 'from-slate-600 to-gray-700', bg: 'bg-slate-50', badge: 'bg-slate-100 text-slate-700', emoji: '\u{1F4BB}' },
  DISPLAY_RESOURCES: { label: 'Classroom', gradient: 'from-indigo-400 to-blue-500', bg: 'bg-indigo-50', badge: 'bg-indigo-100 text-indigo-700', emoji: '\u{1F4DA}' },
};

export const categoryList = [
  { key: 'ALL', label: 'All Resources', emoji: '\u{1F4DA}' },
  { key: 'SPRING', label: 'Spring', emoji: '\u{1F331}' },
  { key: 'SUMMER', label: 'Summer', emoji: '\u{2600}\u{FE0F}' },
  { key: 'AUTUMN', label: 'Autumn', emoji: '\u{1F342}' },
  { key: 'WINTER', label: 'Winter', emoji: '\u{2744}\u{FE0F}' },
  { key: 'CHRISTMAS', label: 'Christmas', emoji: '\u{1F384}' },
  { key: 'EASTER', label: 'Easter', emoji: '\u{1F430}' },
  { key: 'SPACE', label: 'Space', emoji: '\u{1F680}' },
  { key: 'MATHS', label: 'Maths', emoji: '\u{1F522}' },
  { key: 'ENGLISH', label: 'English', emoji: '\u{270D}\u{FE0F}' },
  { key: 'SCIENCE', label: 'Science', emoji: '\u{1F52C}' },
  { key: 'PHONICS', label: 'Phonics', emoji: '\u{1F524}' },
  { key: 'DINOSAURS', label: 'Dinosaurs', emoji: '\u{1F995}' },
  { key: 'ANIMALS', label: 'Animals', emoji: '\u{1F43E}' },
  { key: 'OCEANS', label: 'Oceans', emoji: '\u{1F30A}' },
  { key: 'WEATHER', label: 'Weather', emoji: '\u{1F324}\u{FE0F}' },
  { key: 'HISTORY', label: 'History', emoji: '\u{1F3DB}\u{FE0F}' },
  { key: 'GEOGRAPHY', label: 'Geography', emoji: '\u{1F30D}' },
  { key: 'NATURE', label: 'Nature', emoji: '\u{1F33F}' },
  { key: 'ART', label: 'Art', emoji: '\u{1F3A8}' },
  { key: 'MUSIC', label: 'Music', emoji: '\u{1F3B5}' },
  { key: 'COMPUTING_LABELS', label: 'Computing', emoji: '\u{1F4BB}' },
  { key: 'DISPLAY_RESOURCES', label: 'Classroom', emoji: '\u{1F4DA}' },
];

export function getCategoryConfig(category) {
  return categoryConfig[category] || { label: category, gradient: 'from-gray-400 to-gray-500', bg: 'bg-gray-50', badge: 'bg-gray-100 text-gray-700', emoji: '\u{1F4C4}' };
}
